/**
 * Put `FirebaseApp.configure()` into AppDelegate.swift, which the
 * @react-native-firebase/app plugin no longer manages to do on its own.
 *
 * WHAT BREAKS WITHOUT THIS. Prebuild prints, and then continues:
 *
 *   » ios: @react-native-firebase/app: Unable to determine correct Firebase
 *     insertion point in AppDelegate.swift. Skipping Firebase addition.
 *
 * It is a warning, so the build succeeds and the app installs — and then FCM
 * never mints a device token, because the native Firebase app was never
 * initialised. Push is silently dead in a build that otherwise looks fine.
 *
 * WHY IT FAILS. The plugin (21.x) anchors on a line that Expo's AppDelegate
 * template used to contain:
 *
 *   const methodInvocationLineMatcher = /(?:self\.moduleName\s*=\s*"([^"]*)")/g
 *
 * SDK 53 rewrote the template around ExpoReactNativeFactory and moved the
 * module name into ReactNativeDelegate, so `self.moduleName = "main"` is simply
 * not there any more and the anchor never matches. Nothing is wrong with this
 * project's configuration; the upstream anchor is stale.
 *
 * WHY IT ANCHORS ON THE FUNCTION INSTEAD. Rather than matching another line
 * that a future template could also rename, this finds the
 * didFinishLaunchingWithOptions declaration and inserts at the top of its body,
 * handling both the one-line and the wrapped multi-line signature. That is the
 * contract Firebase actually documents — configure before anything else in
 * application:didFinishLaunchingWithOptions: — rather than a coincidence of
 * where a particular assignment happened to sit.
 *
 * ONLY WHEN THE PLIST IS THERE. FirebaseApp.configure() with no
 * GoogleService-Info.plist in the bundle does not degrade — it raises a fatal
 * error and the app dies on launch. Both Firebase files are gitignored, so a CI
 * build without the secret configured has no plist, and injecting
 * unconditionally would turn "push doesn't work" into "the app doesn't start".
 * This is a no-op unless ios.googleServicesFile is set, which app.config.js
 * only does when the file is actually on disk.
 */

const { withAppDelegate } = require('expo/config-plugins');

const IMPORT = 'import FirebaseCore';
const CALL = 'FirebaseApp.configure()';

/**
 * Insert `FirebaseApp.configure()` as the first statement of
 * application(_:didFinishLaunchingWithOptions:).
 *
 * Returns null when the file has no such method, so the caller can fail with a
 * useful message instead of writing a file that silently does nothing.
 */
function injectConfigure(src) {
  if (src.includes(CALL)) return src; // already done, by us or by upstream

  const decl = /func\s+application\s*\(/g;
  let match;
  while ((match = decl.exec(src)) !== null) {
    // Walk the parameter list to its matching ")", so a signature wrapped over
    // several lines is found the same way as a single-line one.
    let depth = 0;
    let i = match.index + match[0].length - 1;
    for (; i < src.length; i++) {
      if (src[i] === '(') depth++;
      else if (src[i] === ')' && --depth === 0) break;
    }
    const signature = src.slice(match.index, i + 1);
    if (!signature.includes('didFinishLaunchingWithOptions')) continue;

    // The body opens at the first "{" after the return type.
    const brace = src.indexOf('{', i);
    if (brace === -1) continue;

    // Match the indentation of the line the body opened on, plus one level.
    const lineStart = src.lastIndexOf('\n', match.index) + 1;
    const indent = `${src.slice(lineStart, match.index).match(/^\s*/)[0]}  `;

    return `${src.slice(0, brace + 1)}\n${indent}// @generated by withFirebaseAppDelegate\n${indent}${CALL}\n${src.slice(brace + 1)}`;
  }

  return null;
}

function injectImport(src) {
  if (src.includes(IMPORT)) return src;
  // After the last top-level import rather than after `import Expo`
  // specifically: the upstream plugin keys off Expo's import and that is
  // exactly the kind of assumption this file exists to stop repeating.
  const imports = [...src.matchAll(/^import .+$/gm)];
  if (!imports.length) return `${IMPORT}\n${src}`;
  const last = imports[imports.length - 1];
  const at = last.index + last[0].length;
  return `${src.slice(0, at)}\n${IMPORT}${src.slice(at)}`;
}

module.exports = function withFirebaseAppDelegate(config) {
  if (!config.ios?.googleServicesFile) return config;

  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `[withFirebaseAppDelegate] Expected a Swift AppDelegate, got "${cfg.modResults.language}". ` +
          'Remove this plugin, or teach it the other language — do not ship without it, ' +
          'or Firebase will not initialise and push will fail silently.',
      );
    }

    const withCall = injectConfigure(cfg.modResults.contents);
    if (withCall === null) {
      // Loud, on purpose. The whole point of this plugin is that the upstream
      // version of this problem was a warning nobody saw until push was dead on
      // a device.
      throw new Error(
        '[withFirebaseAppDelegate] Could not find application(_:didFinishLaunchingWithOptions:) ' +
          'in AppDelegate.swift, so FirebaseApp.configure() was not inserted. The Expo template ' +
          'has changed again — update packages/config/plugins/withFirebaseAppDelegate.js.',
      );
    }

    cfg.modResults.contents = injectImport(withCall);
    return cfg;
  });
};
