/**
 * Give the Firebase pods modular headers, so `pod install` can integrate them
 * as static libraries.
 *
 * WHAT BREAKS WITHOUT THIS. `pod install` fails outright:
 *
 *   [!] The following Swift pods cannot yet be integrated as static libraries:
 *   The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which
 *   does not define modules.
 *
 * GoogleUtilities is Objective-C without a module map. Swift can only import a
 * static-library pod that defines modules, so the Swift half of Firebase cannot
 * see the C half, and CocoaPods refuses rather than producing a project that
 * fails later in the compiler. `:modular_headers => true` makes CocoaPods
 * synthesise the module map for exactly the pods that need one — narrower than
 * the global `use_modular_headers!`, which changes header resolution for all
 * ~140 pods in this project and is a much larger blast radius for the same fix.
 *
 * WHY IT IS UNCONDITIONAL, unlike withFirebaseAppDelegate. These pods arrive
 * through autolinking, straight from node_modules, and are installed whether or
 * not GoogleService-Info.plist exists or the @react-native-firebase config
 * plugins are active — the failing build had no plist at all. The gate is
 * therefore whether @react-native-firebase/app is a dependency, not whether
 * Firebase is configured. Every pod named below appears in that build's install
 * list, so none of these lines pulls in something that was not already there.
 *
 * WHY A PLUGIN AND NOT AN EDIT. The Podfile is generated by `expo prebuild` and
 * gitignored; anything written into it by hand is erased by the next --clean.
 */

const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const MARKER = '# @generated by withFirebasePods';

// The Swift-facing Firebase pods and the Objective-C ones they import.
const PODS = [
  'FirebaseCore',
  'FirebaseCoreInternal',
  'FirebaseCoreExtension',
  'FirebaseInstallations',
  'FirebaseMessaging',
  'GoogleUtilities',
  'GoogleDataTransport',
  'nanopb',
];

function addModularHeaders(podfile) {
  if (podfile.includes(MARKER)) return podfile;

  const target = /^target\s+['"][^'"]+['"]\s+do\s*$/m.exec(podfile);
  if (!target) return null;

  const at = target.index + target[0].length;
  const block = [
    '',
    `  ${MARKER} — see packages/config/plugins/withFirebasePods.js`,
    ...PODS.map((p) => `  pod '${p}', :modular_headers => true`),
  ].join('\n');

  return podfile.slice(0, at) + block + podfile.slice(at);
}

module.exports = function withFirebasePods(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfile, 'utf8');
      const next = addModularHeaders(contents);

      if (next === null) {
        // Loud on purpose: the alternative is a green prebuild followed by a
        // pod install that fails several minutes later with an error that says
        // nothing about this file.
        throw new Error(
          '[withFirebasePods] Could not find the app target in the generated Podfile, ' +
            'so the Firebase pods were left without modular headers and `pod install` will ' +
            'fail. The Expo template has changed — update ' +
            'packages/config/plugins/withFirebasePods.js.',
        );
      }

      fs.writeFileSync(podfile, next);
      return cfg;
    },
  ]);
};

module.exports._addModularHeaders = addModularHeaders;
