/**
 * Shared error codes returned by the EyeGo API.
 * Use these constants instead of hardcoding strings in app code.
 */
export const ErrorCodes = {
  // OTP
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  // Booking
  SEAT_TAKEN: 'SEAT_TAKEN',
  SEAT_UNAVAILABLE: 'SEAT_UNAVAILABLE',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  // Payment
  INSUFFICIENT_WALLET: 'INSUFFICIENT_WALLET',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',
  // Trip
  TRIP_FULL: 'TRIP_FULL',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  TRIP_ALREADY_COMPLETED: 'TRIP_ALREADY_COMPLETED',
  // Driver
  NO_VEHICLE: 'NO_VEHICLE',
  NEGATIVE_WALLET_BALANCE: 'NEGATIVE_WALLET_BALANCE',
  DRIVER_OFFLINE: 'DRIVER_OFFLINE',
  // Auth
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  // Invite
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
