'use strict';

const prisma = require('../../config/database');
const supply = require('../../services/supply-index.service');
const { seatOccupyingWhere } = require('../../utils/booking-status');

/**
 * The demand heat map — where riders are actually asking for cars.
 *
 * THREE BUGS THIS FIXES, all of which showed up as the same symptom: "I turned
 * the heat icon on and the circle sat on a street a short distance away from me,
 * even though my own phone is the only thing requesting rides."
 *
 * 1. IT READ THE WRONG COORDINATES. Demand was taken from
 *    `booking.trip.route.origin{Lat,Lng}` — the ORIGIN OF THE ROUTE, which is a
 *    scheduled-bus concept. An on-demand ride has `routeId: null` (see
 *    modules/rides/rides.service.js, which creates the Trip with no route at
 *    all), so the entire product we actually sell contributed ZERO demand, and
 *    the `where` clause on `trip.route.origin*` excluded those bookings before
 *    anything else could go wrong. Demand now comes from the booking's own
 *    pickup, then the trip's pickup, and only falls back to the route origin for
 *    genuine bus bookings — the same precedence the rest of the codebase uses.
 *
 * 2. IT MOVED EVERY POINT TO A GRID CORNER. Points were snapped with
 *    `Math.round(lat / 0.01) * 0.01` and the CELL CENTRE was then returned as the
 *    cell's position. At Ghana's latitude 0.01° is ~1.1 km, so a snapped point
 *    could be reported up to ~780 m from the request it represents — "a street a
 *    short distance away", exactly. Bucketing is still how cells are aggregated
 *    (that is what makes it a heat map), but a cell now reports the MEAN of the
 *    real coordinates that fell into it, so a single request produces a circle
 *    precisely on that request.
 *
 * 3. IT DREW CIRCLES WHERE THERE WAS NO DEMAND. Cells were emitted for the union
 *    of demand and supply buckets, so a bucket containing only the driver's own
 *    parked car became a cell with `weight: 0` — and the client renders every
 *    cell it is given with a floor of 0.1 opacity (components/DemandOverlay.tsx).
 *    The driver was looking at a heat blob generated by their own snapped
 *    position. Supply-only cells are no longer returned; supply exists here to
 *    divide demand, not to create it.
 *
 * SHARED ROOT WITH THE DISPATCH BUG: supply is now read through
 * `supply-index.service`, the same index `matcher.service` searches, instead of
 * the legacy `drivers:online` geoset. That set has no presence TTL, so drivers
 * who closed the app hours ago still counted as supply here and diluted the
 * ratio. One geo source, one lat/lng convention (`[lng, lat]`, enforced inside
 * the index service), for both features.
 */

// Bucket step in degrees: ~0.01° ≈ 1.1 km at Ghana's latitude. Used ONLY to
// group nearby requests together — never as the reported position of a cell.
const BUCKET_DEG = 0.01;

// How far back to consider booking demand (hours).
const DEMAND_LOOKBACK_HOURS = 24;

/** Bucket key for a coordinate pair. Grouping only — see the note above. */
function bucketKey(lat, lng) {
  const latKey = Math.round(lat / BUCKET_DEG);
  const lngKey = Math.round(lng / BUCKET_DEG);
  return `${latKey}:${lngKey}`;
}

/**
 * The coordinates this booking's demand belongs at.
 *
 * Precedence matters. A group-hub joiner books with their own precise pickup
 * (`booking.pickupLat/Lng`); an ordinary on-demand rider has the same values
 * copied onto their booking; a scheduled bus passenger has neither and belongs at
 * the trip's pickup, or failing that the route's origin.
 */
function demandPointFor(booking) {
  const candidates = [
    [booking.pickupLat, booking.pickupLng],
    [booking.trip?.pickupLat, booking.trip?.pickupLng],
    [booking.trip?.route?.originLat, booking.trip?.route?.originLng],
  ];
  for (const [lat, lng] of candidates) {
    if (Number.isFinite(lat) && Number.isFinite(lng)) return { lat, lng };
  }
  return null;
}

/**
 * Aggregate recent booking density around a centre point.
 *
 * Returns an array of cell objects:
 *   { lat, lng, weight (booking count in the cell),
 *     driversNearby (live drivers from the dispatch supply index),
 *     demandSupplyRatio (bookings / max(1, driversNearby)) }
 *
 * @param {Object} opts
 * @param {number} opts.lat    Centre latitude
 * @param {number} opts.lng    Centre longitude
 * @param {number} [opts.radiusKm=5]  Search radius in km
 */
async function aggregateDemand({ lat, lng, radiusKm = 5 }) {
  // Approx degrees for the radius (1° ≈ 111 km). A latitude-only approximation
  // is fine here: it is a pre-filter, and it is deliberately generous.
  const degRadius = radiusKm / 111;

  const latMin = lat - degRadius;
  const latMax = lat + degRadius;
  const lngMin = lng - degRadius;
  const lngMax = lng + degRadius;

  // ── Demand: recent live/settled bookings (last N hours) ────────────
  const since = new Date(Date.now() - DEMAND_LOOKBACK_HOURS * 60 * 60 * 1000);

  /**
   * The bounding box is applied to the BOOKING's own pickup or the TRIP's
   * pickup, because those are the columns the demand point is read from. The old
   * query filtered on `trip.route.origin*` — a relation an on-demand trip does
   * not have — which is a join that silently returns nothing rather than an
   * error, and is why this endpoint could return a driver's own position and
   * nothing else.
   */
  const inBox = (latField, lngField) => ({
    [latField]: { gte: latMin, lte: latMax },
    [lngField]: { gte: lngMin, lte: lngMax },
  });

  const bookings = await prisma.booking.findMany({
    where: {
      createdAt: { gte: since },
      // Demand means "a rider committed to a ride here". `seatOccupyingWhere()`
      // is the one shared definition of that (and it already includes COMPLETED,
      // since a finished ride is still evidence of demand), so this cannot drift
      // from the seat-accounting invariants. The old inline
      // `['CONFIRMED','COMPLETED','PAID']` missed BOARDED and SEAT_HELD.
      ...seatOccupyingWhere(),
      OR: [
        inBox('pickupLat', 'pickupLng'),
        { trip: inBox('pickupLat', 'pickupLng') },
        { trip: { route: inBox('originLat', 'originLng') } },
      ],
    },
    select: {
      pickupLat: true,
      pickupLng: true,
      trip: {
        select: {
          pickupLat: true,
          pickupLng: true,
          route: { select: { originLat: true, originLng: true } },
        },
      },
    },
    // A heat map is a shape, not a census; cap the work this endpoint can do.
    take: 2000,
  });

  // key → { count, latSum, lngSum }. The sums are what let a cell report where
  // the requests really were instead of where the grid corner is.
  const demandBuckets = new Map();

  for (const b of bookings) {
    const point = demandPointFor(b);
    if (!point) continue;
    // Re-check the point actually used: the OR above may have matched on a
    // different column than the one demandPointFor picked.
    if (point.lat < latMin || point.lat > latMax || point.lng < lngMin || point.lng > lngMax) continue;

    const key = bucketKey(point.lat, point.lng);
    const cell = demandBuckets.get(key) ?? { count: 0, latSum: 0, lngSum: 0 };
    cell.count += 1;
    cell.latSum += point.lat;
    cell.lngSum += point.lng;
    demandBuckets.set(key, cell);
  }

  if (demandBuckets.size === 0) return [];

  // ── Supply: live drivers from the dispatch supply index ────────────
  // Same index dispatch searches, so "drivers nearby" here means the same thing
  // as "drivers who could be offered this ride". Presence-filtered, so a driver
  // who closed the app is not counted.
  let onlineDrivers = [];
  try {
    onlineDrivers = await supply.nearbyDrivers(lat, lng, radiusKm, 200, { withCoords: true });
  } catch (_) {
    // No supply data — demand still stands on its own.
  }

  const supplyBuckets = new Map(); // key → count
  for (const d of onlineDrivers) {
    if (!Number.isFinite(d.lat) || !Number.isFinite(d.lng)) continue;
    const key = bucketKey(d.lat, d.lng);
    supplyBuckets.set(key, (supplyBuckets.get(key) || 0) + 1);
  }

  // ── Combine ────────────────────────────────────────────────────────
  // Demand cells only. A bucket with supply and no demand is not "hot" — and
  // returning it put a heat circle on top of the driver's own parked car.
  const cells = [];
  for (const [key, cell] of demandBuckets) {
    const drivers = supplyBuckets.get(key) || 0;
    const demandSupplyRatio = cell.count / Math.max(1, drivers);
    cells.push({
      // The mean of the real request coordinates in this cell — for a single
      // request, that IS the request's own position.
      lat: Math.round((cell.latSum / cell.count) * 1e6) / 1e6,
      lng: Math.round((cell.lngSum / cell.count) * 1e6) / 1e6,
      weight: cell.count,
      driversNearby: drivers,
      demandSupplyRatio: Math.round(demandSupplyRatio * 100) / 100,
    });
  }

  // Sort by weight descending (hottest areas first)
  cells.sort((a, b) => b.weight - a.weight);

  return cells;
}

module.exports = { aggregateDemand };
